#requires -Version 5.1
<#
.SYNOPSIS
  Renames the project from "ZipFileORM" to "ZipFileORM" throughout all source
  files, package files, scripts, and documentation inside ZipFileORM/.

  Scope:
  - Content substitutions in .pas, .dpk, .dproj, .groupproj, .lpk, .dpr,
    .lpr, .ps1, .md, .rc, .json, .local (text files)
  - Physical file renames for packages, src, tests, testcase
  - Skips sdk/, deps/, dll/, BCC/, Library/, Lib/, .cursor/, .wolf/, .svn/
  - Does NOT rename the root directory "ZipFileORM/" (filesystem path)
  - Does NOT rename component class names (TZipFileORM, TGzipFile etc.)
  - Does NOT rename icons/TZIPFILE.bmp, icons/TGZIPFILE.bmp (resource sources)
  - Does NOT rename build artifacts (.ppu/.o/.dcu/.exe/.bpl/.dcp/.rsj)
#>

[CmdletBinding(SupportsShouldProcess)]
param([switch]$DryRun)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot  # ZipFileORM/

# ---------------------------------------------------------------------------
# Content substitution function
# Rules are applied in ORDER; each pass processes only what remains.
# All pattern matches are CASE-SENSITIVE (-creplace) to avoid accidentally
# modifying GzipFile, TGzipFile, TZIPFILE etc.
# ---------------------------------------------------------------------------
function Update-Content([string]$text) {

    # Pass 1 — lowercase compound patterns with version suffix
    # 'dclZipFileORMD' must run before 'ZipFileORMD' so dcl prefix is set correctly.
    $text = $text -creplace 'dclZipFileORMD', 'dclZipFileORMD'
    $text = $text -creplace 'ZipFileORMD',    'ZipFileORMD'

    # Pass 2 — lowercase named compounds
    $text = $text -creplace 'ZipFileORMReg',  'ZipFileORMReg'
    $text = $text -creplace 'ZipFileORMpkg',  'ZipFileORMpkg'
    $text = $text -creplace 'ZipFileORM_',    'ZipFileORM_'
    $text = $text -creplace 'ZipFileORM-',    'ZipFileORM-'

    # Pass 3 — mixed-case exact Lazarus/test names (run before generic rules)
    $text = $text -creplace 'ZipFileORMPkg',   'ZipFileORMPkg'
    $text = $text -creplace 'ZipFileORMTests', 'ZipFileORMTests'

    # Pass 4 — namespace prefix ZipFileORM. (handles ZipFileORM.UTF8, ZipFileORM.Events, etc.)
    # Case-sensitive: matches capital ZipFileORM. only, NOT gZipFileORM.
    $text = $text -creplace 'ZipFileORM\.', 'ZipFileORM.'

    # Pass 5 — exact unit declaration (before generic standalone rule)
    $text = $text -creplace 'unit ZipFileORM;', 'unit ZipFileORM;'

    # Pass 6 — standalone capital ZipFileORM not followed by '.' or word character
    # Handles: uses ZipFileORM,   requires ZipFileORM;   'ZipFileORM'   (ZipFileORM)
    # Does NOT match: ZipFileORM.UTF8  ZipFileORM  ZipFileORMPkg  (already done above)
    $text = $text -creplace 'ZipFileORM(?![.\w])', 'ZipFileORM'

    # Pass 7 — remaining lowercase 'ZipFileORM' (all-lowercase occurrences only)
    # Case-sensitive: matches "ZipFileORM" but NOT "GzipFile", "ZipFileORM" etc.
    # Handles: uses ZipFileORM,   ZipFileORM.pas   {$R ZipFileORM.dcr}   prose
    $text = $text -creplace 'ZipFileORM', 'ZipFileORM'

    return $text
}

# ---------------------------------------------------------------------------
# Directories to skip (vendor / build output / IDE config / binary)
# ---------------------------------------------------------------------------
$skipDirs = @('sdk','deps','dll','BCC','Library','Lib','.cursor','.wolf','.svn','.git','.workspace')

function Test-SkipPath([string]$fullPath) {
    foreach ($s in $skipDirs) {
        if ($fullPath -like "*\$s\*" -or $fullPath -like "*/$s/*") { return $true }
    }
    return $false
}

# ---------------------------------------------------------------------------
# File extensions to process for content substitution
# ---------------------------------------------------------------------------
$textExts = @('*.pas','*.dpk','*.dproj','*.groupproj','*.lpk','*.dpr','*.lpr','*.ps1','*.md','*.rc','*.json','*.local','*.txt','*.lpi')

# ---------------------------------------------------------------------------
# Filename rename function — uses case-sensitive anchored patterns.
# Returns early on first match to prevent double-substitution.
# Does NOT apply generic catch-alls that would re-match already-changed names.
# ---------------------------------------------------------------------------
function Get-NewName([string]$name) {
    # Skip build artifacts (they will be regenerated by the next build)
    $artifactExts = @('.ppu','.o','.dcu','.exe','.bpl','.dcp','.bpi','.rsj','.obj','.dres')
    $ext = [IO.Path]::GetExtension($name).ToLower()
    if ($ext -in $artifactExts) { return $name }

    # Skip component icons (TZIPFILE.bmp etc.) — class names stay the same
    if ($name -cmatch '^T[A-Z]+FILE\.(bmp|png)$') { return $name }

    # --- Lowercase patterns (case-sensitive anchored) ---
    if ($name -cmatch '^dclZipFileORMD(\d+)(.*)$')   { return "dclZipFileORMD$($Matches[1])$($Matches[2])" }
    if ($name -cmatch '^ZipFileORMD(\d+)(.*)$')        { return "ZipFileORMD$($Matches[1])$($Matches[2])" }
    if ($name -cmatch '^ZipFileORMReg(.*)$')            { return "ZipFileORMReg$($Matches[1])" }
    if ($name -cmatch '^ZipFileORMpkg(.*)$')            { return "ZipFileORMpkg$($Matches[1])" }
    if ($name -cmatch '^ZipFileORM_(.*)$')              { return "ZipFileORM_$($Matches[1])" }
    if ($name -cmatch '^ZipFileORM-(.*)$')              { return "ZipFileORM-$($Matches[1])" }
    if ($name -cmatch '^ZipFileORM\.(.*)$')             { return "ZipFileORM.$($Matches[1])" }

    # --- Mixed/upper-case patterns ---
    if ($name -cmatch '^ZipFileORMPkg(.*)$')            { return "ZipFileORMPkg$($Matches[1])" }
    if ($name -cmatch '^ZipFileORMTests(.*)$')          { return "ZipFileORMTests$($Matches[1])" }
    if ($name -cmatch '^ZipFileORM\.(.*)$')             { return "ZipFileORM.$($Matches[1])" }

    # --- Mixed-case variant in Zipfile.dcr ---
    if ($name -cmatch '^Zipfile\.(.*)$')             { return "ZipFileORM.$($Matches[1])" }

    # --- Lazarus resource files: tZipFileORM.lrs, tZipFileORM.xpm ---
    if ($name -cmatch '^tZipFileORM\.(.*)$')            { return "tZipFileORM.$($Matches[1])" }

    return $name  # no change
}

# ---------------------------------------------------------------------------
# Phase 1 — Content substitutions
# ---------------------------------------------------------------------------
Write-Host "=== Phase 1: Content substitutions ===" -ForegroundColor Cyan

$files = Get-ChildItem $root -Recurse -Include $textExts -File |
         Where-Object { -not (Test-SkipPath $_.FullName) }

$changed = 0
foreach ($f in $files) {
    try { $raw = [System.IO.File]::ReadAllText($f.FullName) }
    catch { Write-Warning "Cannot read $($f.Name): $_"; continue }

    $updated = Update-Content $raw
    if ($updated -ne $raw) {
        $rel = $f.FullName.Replace($root, '.')
        if ($DryRun) {
            Write-Host "  [DRY] $rel"
        } else {
            $enc = [System.Text.UTF8Encoding]::new($false)  # UTF-8 without BOM
            [System.IO.File]::WriteAllText($f.FullName, $updated, $enc)
            Write-Host "  UPDATED: $rel" -ForegroundColor Green
        }
        $changed++
    }
}
Write-Host "Phase 1 done: $changed files updated.`n" -ForegroundColor Cyan

# ---------------------------------------------------------------------------
# Phase 2 — File renames
# ---------------------------------------------------------------------------
Write-Host "=== Phase 2: File renames ===" -ForegroundColor Cyan

$allFiles = Get-ChildItem $root -Recurse -File |
            Where-Object { -not (Test-SkipPath $_.FullName) }

$renamed = 0
foreach ($f in $allFiles) {
    $newName = Get-NewName $f.Name
    if ($newName -ne $f.Name) {
        $newPath = Join-Path $f.DirectoryName $newName
        if ($DryRun) {
            Write-Host "  [DRY] $($f.Name) -> $newName"
        } else {
            if (Test-Path $f.FullName) {
                Rename-Item -Path $f.FullName -NewName $newName -Force
                Write-Host "  RENAMED: $($f.Name) -> $newName" -ForegroundColor Yellow
                $renamed++
            }
        }
    }
}
Write-Host "Phase 2 done: $renamed files renamed." -ForegroundColor Cyan

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
Write-Host ""
Write-Host "=== Done ===" -ForegroundColor Green
Write-Host "Content updates: $changed  |  File renames: $renamed"
if ($DryRun) { Write-Host "(DRY RUN - no files modified)" -ForegroundColor Yellow }
